[package]
name = "etcommon-hexutil"
version = "0.2.0"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Hex helper functions."
repository = "https://github.com/ethereumproject/etcommon"

[lib]
name = "hexutil"