[package]
name = "etcommon-block"
version = "0.3.1"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Block and transaction types for Ethereum."
repository = "https://github.com/ethereumproject/etcommon-rs"

[lib]
name = "block"

[dependencies]
sha3 = "0.6"
secp256k1-plus = "0.5"
etcommon-bigint = { version = "0.2", path = "../bigint" }
etcommon-rlp = { version = "0.2", path = "../rlp" }
etcommon-bloom = { version = "0.2", path = "../bloom" }
etcommon-trie = { version = "0.3", path = "../trie" }
blockchain = "0.1"

[dev-dependencies]
rand = "0.3.12"
etcommon-hexutil = "0.2"