[package]
name = "etcommon-block"
version = "0.2.0"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Block and transaction types for Ethereum."
repository = "https://github.com/ethereumproject/etcommon"

[lib]
name = "block"

[dependencies]
sha3 = "0.6"
secp256k1-plus = "0.5"
etcommon-bigint = "0.2"
etcommon-rlp = "0.2"
etcommon-bloom = "0.2"

[dev-dependencies]
etcommon-hexutil = "0.2"