[package]
name = "etcommon-bloom"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Log bloom implementation for Ethereum."
repository = "https://github.com/ethereumproject/etcommon"

[dependencies]
etcommon-rlp = "0.1.1"
etcommon-bigint = "0.1"
etcommon-crypto = "0.1"
etcommon-util = "0.1"