[package]
name = "etcommon-bigint"
version = "0.1.5"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Big integer (256-bit and 512-bit) implementation for SputnikVM and other Ethereum Classic clients."
repository = "https://github.com/ethereumproject/etcommon"

[dependencies]
heapsize = "0.4"
byteorder = "1.0"
rand = "0.3.12"
libc = "0.2"
etcommon-rlp = { path = '../rlp' }
etcommon-util = { path = '../util' }

[features]
x64asm_arithmetic=[]
rust_arithmetic=[]