[package]
name = "etcommon-bigint"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Big integer (256-bit and 512-bit) implementation for SputnikVM and other Ethereum Classic clients."
repository = "https://github.com/ethereumproject/etcommon"

[dependencies]
etcommon-rlp = { path = '../rlp' }
etcommon-util = { path = '../util' }